// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	code.proto
	oss.proto

It has these top-level messages:
	GenAuthTokenReq
	GenAuthTokenRsp
	ValidAuthReq
	ValidAuthRsp
	SetEventsReq
	SetEventsRsp
	GetEventsReq
	GetEventsRsp
	DelEventsReq
	DelEventsRsp
	UpdateEventsReq
	UpdateEventsRsp
	UpdateEventsRtmpReq
	UpdateEventsRtmpRsp
	RtmpAuthReq
	RtmpAuthRsp
	SetEventsFileReq
	SetEventsFileRsp
	GetEventsFileReq
	GetEventsFileRsp
	DelEventsFileReq
	DelEventsFileRsp
	TranscodeReq
	TranscodeRsp
	GetTranscodeTaskReq
	GetTranscodeTaskRsp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_SERVER_ERROR ErrorCode = 101
	ErrorCode_AUTH_FAILED  ErrorCode = 300
)

var ErrorCode_name = map[int32]string{
	101: "SERVER_ERROR",
	300: "AUTH_FAILED",
}
var ErrorCode_value = map[string]int32{
	"SERVER_ERROR": 101,
	"AUTH_FAILED":  300,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto1.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventStatus int32

const (
	EventStatus_EVENT_SUCCESS        EventStatus = 2000
	EventStatus_EVENT_BEGIN          EventStatus = 2001
	EventStatus_EVENT_TO_MONITOR_SUC EventStatus = 2002
	EventStatus_EVENT_UPLOAD_BEGIN   EventStatus = 2003
	EventStatus_EVENT_UPLOAD_SUC     EventStatus = 2004
	EventStatus_EVENT_TRANSCODE_SUC  EventStatus = 2005
)

var EventStatus_name = map[int32]string{
	2000: "EVENT_SUCCESS",
	2001: "EVENT_BEGIN",
	2002: "EVENT_TO_MONITOR_SUC",
	2003: "EVENT_UPLOAD_BEGIN",
	2004: "EVENT_UPLOAD_SUC",
	2005: "EVENT_TRANSCODE_SUC",
}
var EventStatus_value = map[string]int32{
	"EVENT_SUCCESS":        2000,
	"EVENT_BEGIN":          2001,
	"EVENT_TO_MONITOR_SUC": 2002,
	"EVENT_UPLOAD_BEGIN":   2003,
	"EVENT_UPLOAD_SUC":     2004,
	"EVENT_TRANSCODE_SUC":  2005,
}

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}
func (x EventStatus) String() string {
	return proto1.EnumName(EventStatus_name, int32(x))
}
func (x *EventStatus) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(EventStatus_value, data, "EventStatus")
	if err != nil {
		return err
	}
	*x = EventStatus(value)
	return nil
}
func (EventStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterEnum("proto.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto1.RegisterEnum("proto.EventStatus", EventStatus_name, EventStatus_value)
}

func init() { proto1.RegisterFile("code.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8c, 0xcd, 0x4d, 0xc4, 0x30,
	0x10, 0x46, 0x05, 0x12, 0x07, 0x26, 0x20, 0x5b, 0x03, 0x08, 0x68, 0x21, 0x07, 0xa8, 0xc1, 0x38,
	0x03, 0x44, 0x0a, 0x36, 0xb2, 0x9d, 0x5c, 0x2d, 0x44, 0x72, 0xc5, 0xc8, 0x98, 0xad, 0x65, 0x8b,
	0xd8, 0x62, 0xf6, 0xb7, 0x9f, 0x95, 0x93, 0x5c, 0xf6, 0x34, 0xd2, 0x7b, 0xf3, 0x3e, 0x80, 0xef,
	0xd0, 0x0f, 0x4f, 0xbf, 0x31, 0xa4, 0x80, 0x17, 0xe3, 0x29, 0x9f, 0xe1, 0x92, 0x62, 0x0c, 0x51,
	0x86, 0x7e, 0x40, 0x0e, 0x57, 0x96, 0x4c, 0x47, 0xc6, 0x93, 0x31, 0xda, 0xf0, 0x4c, 0x0a, 0xd1,
	0xba, 0x77, 0xff, 0x2a, 0xea, 0x86, 0x2a, 0xbe, 0x3a, 0x2f, 0x97, 0x67, 0x50, 0xd0, 0x62, 0xf8,
	0x49, 0x36, 0x7d, 0xa5, 0xff, 0x3f, 0x44, 0xb8, 0xa6, 0x8e, 0x94, 0xf3, 0xb6, 0x95, 0x92, 0xac,
	0xe5, 0x6b, 0x96, 0xab, 0x89, 0xbd, 0xd0, 0x5b, 0xad, 0xf8, 0x86, 0xe1, 0x23, 0xdc, 0x4e, 0xc4,
	0x69, 0xff, 0xa1, 0x55, 0xed, 0xb4, 0xc9, 0x01, 0xdf, 0x32, 0xbc, 0x07, 0x9c, 0x54, 0xfb, 0xd9,
	0x68, 0x51, 0xcd, 0xcd, 0x8e, 0xe1, 0x1d, 0xf0, 0x13, 0x91, 0xff, 0xf7, 0x0c, 0x1f, 0xe0, 0x66,
	0x9e, 0x32, 0x42, 0x59, 0xa9, 0x2b, 0x1a, 0xcd, 0x81, 0x1d, 0x03, 0x00, 0x00, 0xff, 0xff, 0x55,
	0x82, 0xa1, 0x2d, 0xdf, 0x00, 0x00, 0x00,
}
